[window]
decorations = "none"
dynamic_title = true
opacity = 0.7
startup_mode = "Windowed"  # Ensure this is set to "Windowed"

[window.dimensions]
columns = 100  # Smaller dimensions to ensure changes are noticeable
lines = 40

[window.position]
x = 50
y = 50

[window.padding]
x = 10
y = 10

[font]
size = 13.0  # Change size to see if it applies
