import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
# text = "CellBackground"
#
[window]
decorations = "none"
dynamic_title = true
opacity = 0.7

[window.dimensions]
columns = 110
lines = 42

[window.padding]
x = 4
y = 0
